apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kyler-secrets-provider-name
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "kyler-super-secret-json"
          objectType: "secretsmanager"
        - objectName: "kyler-secret-string"
          objectType: "secretsmanager"