apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyler-secret-fetcher-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::072100331905:role/kyler_eks_role
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kyler-secrets-provider-name
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "kyler-super-secret-json"
          objectType: "secretsmanager"
        - objectName: "kyler-secret-string"
          objectType: "secretsmanager"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyler-secret-fetcher
  labels:
    app: kyler-secret-fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyler-secret-fetcher
  template:
    metadata:
    
      name: kyler-secret-fetcher
      labels:
        app: kyler-secret-fetcher
    spec:
      serviceAccountName: kyler-secret-fetcher-sa
      
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "kyler-secrets-provider-name"
      
      containers:
        - name: kyler-secret-fetcher
          image: kymiddallscripts/secrets-test:latest
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true